//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioteqSofiya931.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.HistoryReaderTicket = new HashSet<HistoryReaderTicket>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdAuthor { get; set; }
        public Nullable<System.DateTime> YearMade { get; set; }
        public Nullable<int> IdCreateBuild { get; set; }
        public Nullable<int> IdJanr { get; set; }
        public Nullable<int> CountPage { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> IdHall { get; set; }
        public Nullable<int> Shelf { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual CreateBuild CreateBuild { get; set; }
        public virtual Hall Hall { get; set; }
        public virtual Janr Janr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryReaderTicket> HistoryReaderTicket { get; set; }
    }
}
