//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioteqSofiya931.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadTicket()
        {
            this.HistoryReaderTicket = new HashSet<HistoryReaderTicket>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> IdReader { get; set; }
        public Nullable<System.DateTime> DateRegistr { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryReaderTicket> HistoryReaderTicket { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
